language: node_js
node_js:
  - 10

dist: trusty
sudo: false
cache: yarn

branches:
  only:
    - release

before_install:
  - openssl aes-256-cbc -K $encrypted_09f96960bb2d_key -iv $encrypted_09f96960bb2d_iv -in env.tar.enc -out env.tar -d
  - tar xvf env.tar

before_deploy:
  - yarn global add netlify-cli
  - yarn build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_PUBLISH_KEY -p --dir ./dist
  on:
    branch: release
